### ISSUE TITLE
No need to wait for data after Wire.requestFrom()

### ISSUE THREAD

**Issue by Koepel** [sparkfun/SparkFun_MLX90614_Arduino_Library#3]
In SparkFunMLX90614.cpp is a while-loop with a delay after the Wire.requestFrom() call. That while-loop is not needed and that delay is not needed.

When the Wire.requestFrom() function returns, the I2C transaction has completely finished and the received data is in the receive buffer in the Wire library. The Wire.read() only reads data from that buffer.

**Comment by nseidle** [comment]
Thanks! Fixed in v1.0.2
