### ISSUE TITLE
ESP32

### ISSUE THREAD

**Issue by kbickham** [sparkfun/SparkFun_MLX90614_Arduino_Library#7]
I believe the the hardware driver on the esp32 (in Arduino IDE) is called differently, not sure about an equivalent function... I think it'll be easier to just directly talk to the module but I got this error on compilation:

SparkFunMLX90614.cpp:284:7: error: 'class TwoWire' has no member named 'end'
....
\Users\Lauren\Documents\Arduino\libraries\SparkFun_MLX90614_Arduino_Library-master\src\SparkFunMLX90614.cpp: In member function 'uint8_t IRTherm::wake()':

C:\Users\Lauren\Documents\Arduino\libraries\SparkFun_MLX90614_Arduino_Library-master\src\SparkFunMLX90614.cpp:284:7: error: 'class TwoWire' has no member named 'end'

  Wire.end(); // stop i2c bus to send wake up request via digital pins

       ^

Using library SparkFun_MLX90614_Arduino_Library-master at version 1.0.2 in folder: C:\Users\Lauren\Documents\Arduino\libraries\SparkFun_MLX90614_Arduino_Library-master 
Using library Wire at version 1.0.1 in folder: C:\Users\Lauren\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.2\libraries\Wire 
Using library SparkFun_AS726X at version 1.0.3 in folder: C:\Users\Lauren\Documents\Arduino\libraries\SparkFun_AS726X 
Using library HX711_ADC at version 1.1.5 in folder: C:\Users\Lauren\Documents\Arduino\libraries\HX711_ADC 
Using library EasyTransfer in folder: C:\Users\Lauren\Documents\Arduino\libraries\EasyTransfer (legacy)
exit status 1
Error compiling for board ESP32 Dev Module.

I would add, I'm not even calling the function from my code.

**Comment by vangalvin** [comment]
I changed line Line 284 - Wire.end(); // stop i2c bus to send wake up request via digital pins
to Wire.endTransmission(true);
That sorted out the issue.

**Comment by tombair** [comment]
I am seeing a similar problem on an ESP8266 board, perhaps this is similar to this[ issue](https://github.com/sparkfun/SparkFun_Qwiic_Keypad_Arduino_Library/issues/1)




Arduino: 1.8.12 (Windows 10), Board: "SparkFun ESP8266 Thing, 80 MHz, Flash, Legacy (new can return nullptr), All SSL ciphers (most compatible), 512KB (FS:32KB OTA:~230KB), v2 Lower Memory, Disabled, None, Only Sketch, 115200"

C:\Users\user\Documents\libraries\SparkFun_MLX90614_Arduino_Library-master\src\SparkFunMLX90614.cpp: In member function 'uint8_t IRTherm::wake()':

C:\Users\user\Documents\libraries\SparkFun_MLX90614_Arduino_Library-master\src\SparkFunMLX90614.cpp:284:7: error: 'class TwoWire' has no member named 'end'

  Wire.end(); // stop i2c bus to send wake up request via digital pins

       ^

exit status 1
Error compiling for board SparkFun ESP8266 Thing.

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by avellinosantiago** [comment]
the change on line Wire.endTransmission(true); worked! thanks
